### ISSUE TITLE
Device mapping: no known devices

### ISSUE THREAD

**Issue by rbharath** [drorlab/tf-singularity#3]
With the bugfixes in #2 I can get a singularity image building and running on Sherlock, but it looks like it's not detecting the GPU. Here's some output from a Sherlock GPU node:

```
(deepchem) [rbharath@gpu-17-35 /scratch/users/rbharath]$ module load singularity
(deepchem) [rbharath@gpu-17-35 /scratch/users/rbharath]$ singularity run tf-gpu.img 
Python 2.7.6 (default, Oct 26 2016, 20:30:19) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> tf.Session(config=tf.ConfigProto(log_device_placement=True))
Device mapping: no known devices.
I tensorflow/core/common_runtime/direct_session.cc:255] Device mapping:

<tensorflow.python.client.session.Session object at 0x7f671d58f210>
```

Would appreciate any help on this one :-)

**Comment by raphtown** [comment]
So I believe this issue stems from having the incorrect NVIDIA driver version.  You can get the correct one by running `sh cuda_8.0.44_linux.run --extract=/path/to/extract` on the CUDA 8.0 run script you downloaded and then using the resulting run files.

**Comment by rbharath** [comment]
@raphtown I updated to use the extracted driver version as you suggested (see updated PR in #2 ), but I'm still seeing the same thing:

```
(deepchem) [rbharath@gpu-9-3 /scratch/users/rbharath]$ singularity run tf-gpu.img 
Python 2.7.6 (default, Oct 26 2016, 20:30:19) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> tf.Session(config=tf.ConfigProto(log_device_placement=True))
Device mapping: no known devices.
I tensorflow/core/common_runtime/direct_session.cc:255] Device mapping:

<tensorflow.python.client.session.Session object at 0x7ff51a3d6210>
```

Any thoughts on what might be going wrong here?

**Comment by rbharath** [comment]
As an update on this thread, `nvidia-smi` is able to spot the GPU, but Tensorflow doesn't load any of the cuda libraries upon import. Maybe a path issue?

```
(deepchem) [rbharath@gpu-9-3 /scratch/users/rbharath]$ singularity run tf-gpu.img
Python 2.7.6 (default, Oct 26 2016, 20:30:19)
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import subprocess
>>> subprocess.call(["nvidia-smi"])
Sat Dec 24 18:54:10 2016
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 367.48                 Driver Version: 367.48                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX TIT...  On   | 0000:86:00.0     Off |                  N/A |
| 26%   35C    P8    14W / 265W |      0MiB /  6082MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
0
>>> import tensorflow as tf
>>> 
```

**Comment by rbharath** [comment]
Looks like the shared-object files aren't getting added to `LD_LIBRARY_PATH` properly. I'm able to see the cuda shared object files in ```/usr/local/cuda/lib64```, but they don't appear in ```ldconfig -p```, explaining why tensorflow can't see them.

```
>>> call("ls /usr/local/cuda/lib64".split())
libOpenCL.so         libcudart_static.a   libcuinj64.so          libcusparse.so.8.0     libnppial.so.8.0.44   libnppig.so          libnppitc.so.8.0        libnvgraph.so.8.0
libOpenCL.so.1       libcudnn.so          libcuinj64.so.8.0      libcusparse.so.8.0.44  libnppicc.so          libnppig.so.8.0      libnppitc.so.8.0.44     libnvgraph.so.8.0.44
libOpenCL.so.1.0     libcudnn.so.5        libcuinj64.so.8.0.44   libcusparse_static.a   libnppicc.so.8.0      libnppig.so.8.0.44   libnpps.so              libnvgraph_static.a
libOpenCL.so.1.0.0   libcudnn.so.5.1.5    libculibos.a           libnppc.so             libnppicc.so.8.0.44   libnppim.so          libnpps.so.8.0          libnvrtc-builtins.so
libcublas.so         libcudnn_static.a    libcurand.so           libnppc.so.8.0         libnppicom.so         libnppim.so.8.0      libnpps.so.8.0.44       libnvrtc-builtins.so.8.0
libcublas.so.8.0     libcufft.so          libcurand.so.8.0       libnppc.so.8.0.44      libnppicom.so.8.0     libnppim.so.8.0.44   libnpps_static.a        libnvrtc-builtins.so.8.0.44
libcublas.so.8.0.45  libcufft.so.8.0      libcurand.so.8.0.44    libnppc_static.a       libnppicom.so.8.0.44  libnppist.so         libnvToolsExt.so        libnvrtc.so
libcublas_device.a   libcufft.so.8.0.44   libcurand_static.a     libnppi.so             libnppidei.so         libnppist.so.8.0     libnvToolsExt.so.1      libnvrtc.so.8.0
libcublas_static.a   libcufft_static.a    libcusolver.so         libnppi.so.8.0         libnppidei.so.8.0     libnppist.so.8.0.44  libnvToolsExt.so.1.0.0  libnvrtc.so.8.0.44
libcudadevrt.a       libcufftw.so         libcusolver.so.8.0     libnppi.so.8.0.44      libnppidei.so.8.0.44  libnppisu.so         libnvblas.so            stubs
libcudart.so         libcufftw.so.8.0     libcusolver.so.8.0.44  libnppi_static.a       libnppif.so           libnppisu.so.8.0     libnvblas.so.8.0
libcudart.so.8.0     libcufftw.so.8.0.44  libcusolver_static.a   libnppial.so           libnppif.so.8.0       libnppisu.so.8.0.44  libnvblas.so.8.0.44
libcudart.so.8.0.44  libcufftw_static.a   libcusparse.so         libnppial.so.8.0       libnppif.so.8.0.44    libnppitc.so         libnvgraph.so
>>> call("ldconfig -p".split())
183 libs found in cache `/etc/ld.so.cache'
        libzmq.so.3 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libzmq.so.3
        libzmq.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libzmq.so
        libz.so.1 (libc6,x86-64) => /lib/x86_64-linux-gnu/libz.so.1
        libz.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libz.so
        libxcb.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libxcb.so.1
        libwind.so.0 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libwind.so.0
        libuuid.so.1 (libc6,x86-64) => /lib/x86_64-linux-gnu/libuuid.so.1
        libutil.so.1 (libc6,x86-64, OS ABI: Linux 2.6.24) => /lib/x86_64-linux-gnu/libutil.so.1
        libutil.so (libc6,x86-64, OS ABI: Linux 2.6.24) => /usr/lib/x86_64-linux-gnu/libutil.so
        libustr-1.0.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libustr-1.0.so.1
        libusb-0.1.so.4 (libc6,x86-64) => /lib/x86_64-linux-gnu/libusb-0.1.so.4
        libudev.so.1 (libc6,x86-64) => /lib/x86_64-linux-gnu/libudev.so.1
        libtsan.so.0 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libtsan.so.0
        libtinfo.so.5 (libc6,x86-64) => /lib/x86_64-linux-gnu/libtinfo.so.5
        libtic.so.5 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libtic.so.5
        libthread_db.so.1 (libc6,x86-64, OS ABI: Linux 2.6.24) => /lib/x86_64-linux-gnu/libthread_db.so.1
        libthread_db.so (libc6,x86-64, OS ABI: Linux 2.6.24) => /usr/lib/x86_64-linux-gnu/libthread_db.so
        libtasn1.so.6 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libtasn1.so.6
        libstdc++.so.6 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libstdc++.so.6
        libssl.so.1.0.0 (libc6,x86-64) => /lib/x86_64-linux-gnu/libssl.so.1.0.0
        libss.so.2 (libc6,x86-64) => /lib/x86_64-linux-gnu/libss.so.2
        libsqlite3.so.0 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libsqlite3.so.0
        libslang.so.2 (libc6,x86-64) => /lib/x86_64-linux-gnu/libslang.so.2
        libsepol.so.1 (libc6,x86-64) => /lib/x86_64-linux-gnu/libsepol.so.1
        libsemanage.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libsemanage.so.1
        libselinux.so.1 (libc6,x86-64) => /lib/x86_64-linux-gnu/libselinux.so.1
        libsasl2.so.2 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libsasl2.so.2
        librtmp.so.0 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/librtmp.so.0
        librt.so.1 (libc6,x86-64, OS ABI: Linux 2.6.24) => /lib/x86_64-linux-gnu/librt.so.1
        librt.so (libc6,x86-64, OS ABI: Linux 2.6.24) => /usr/lib/x86_64-linux-gnu/librt.so
        libroken.so.18 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libroken.so.18
        libresolv.so.2 (libc6,x86-64, OS ABI: Linux 2.6.24) => /lib/x86_64-linux-gnu/libresolv.so.2
        libresolv.so (libc6,x86-64, OS ABI: Linux 2.6.24) => /usr/lib/x86_64-linux-gnu/libresolv.so
        libreadline.so.6 (libc6,x86-64) => /lib/x86_64-linux-gnu/libreadline.so.6
        libquadmath.so.0 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libquadmath.so.0
        libp11-kit.so.0 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libp11-kit.so.0
        libpython2.7.so.1.0 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
        libpython2.7.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libpython2.7.so
        libpthread.so.0 (libc6,x86-64, OS ABI: Linux 2.6.24) => /lib/x86_64-linux-gnu/libpthread.so.0
        libprocps.so.3 (libc6,x86-64) => /lib/x86_64-linux-gnu/libprocps.so.3
        libpopt.so.0 (libc6,x86-64) => /lib/x86_64-linux-gnu/libpopt.so.0
        libpng12.so.0 (libc6,x86-64) => /lib/x86_64-linux-gnu/libpng12.so.0
        libpng12.so.0 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libpng12.so.0
        libpng12.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libpng12.so
        libply.so.2 (libc6,x86-64) => /lib/x86_64-linux-gnu/libply.so.2
        libply-splash-graphics.so.2 (libc6,x86-64) => /lib/x86_64-linux-gnu/libply-splash-graphics.so.2
        libply-splash-core.so.2 (libc6,x86-64) => /lib/x86_64-linux-gnu/libply-splash-core.so.2
        libply-boot-client.so.2 (libc6,x86-64) => /lib/x86_64-linux-gnu/libply-boot-client.so.2
        libpgm-5.1.so.0 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libpgm-5.1.so.0
        libperl.so.5.18 (libc6,x86-64) => /usr/lib/libperl.so.5.18
        libpcreposix.so.3 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libpcreposix.so.3
        libpcre.so.3 (libc6,x86-64) => /lib/x86_64-linux-gnu/libpcre.so.3
        libpcprofile.so (libc6,x86-64, OS ABI: Linux 2.6.24) => /lib/x86_64-linux-gnu/libpcprofile.so
        libpanelw.so.5 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libpanelw.so.5
        libpanel.so.5 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libpanel.so.5
        libpamc.so.0 (libc6,x86-64) => /lib/x86_64-linux-gnu/libpamc.so.0
        libpam_misc.so.0 (libc6,x86-64) => /lib/x86_64-linux-gnu/libpam_misc.so.0
        libpam.so.0 (libc6,x86-64) => /lib/x86_64-linux-gnu/libpam.so.0
        libopcodes-2.24-system.so (libc6,x86-64) => /usr/lib/libopcodes-2.24-system.so
        libnss_nisplus.so.2 (libc6,x86-64, OS ABI: Linux 2.6.24) => /lib/x86_64-linux-gnu/libnss_nisplus.so.2
        libnss_nisplus.so (libc6,x86-64, OS ABI: Linux 2.6.24) => /usr/lib/x86_64-linux-gnu/libnss_nisplus.so
        libnss_nis.so.2 (libc6,x86-64, OS ABI: Linux 2.6.24) => /lib/x86_64-linux-gnu/libnss_nis.so.2
        libnss_nis.so (libc6,x86-64, OS ABI: Linux 2.6.24) => /usr/lib/x86_64-linux-gnu/libnss_nis.so
        libnss_hesiod.so.2 (libc6,x86-64, OS ABI: Linux 2.6.24) => /lib/x86_64-linux-gnu/libnss_hesiod.so.2
        libnss_hesiod.so (libc6,x86-64, OS ABI: Linux 2.6.24) => /usr/lib/x86_64-linux-gnu/libnss_hesiod.so
        libnss_files.so.2 (libc6,x86-64, OS ABI: Linux 2.6.24) => /lib/x86_64-linux-gnu/libnss_files.so.2
        libnss_files.so (libc6,x86-64, OS ABI: Linux 2.6.24) => /usr/lib/x86_64-linux-gnu/libnss_files.so
        libnss_dns.so.2 (libc6,x86-64, OS ABI: Linux 2.6.24) => /lib/x86_64-linux-gnu/libnss_dns.so.2
        libnss_dns.so (libc6,x86-64, OS ABI: Linux 2.6.24) => /usr/lib/x86_64-linux-gnu/libnss_dns.so
        libnss_compat.so.2 (libc6,x86-64, OS ABI: Linux 2.6.24) => /lib/x86_64-linux-gnu/libnss_compat.so.2
        libnss_compat.so (libc6,x86-64, OS ABI: Linux 2.6.24) => /usr/lib/x86_64-linux-gnu/libnss_compat.so
        libnsl.so.1 (libc6,x86-64, OS ABI: Linux 2.6.24) => /lib/x86_64-linux-gnu/libnsl.so.1
        libnsl.so (libc6,x86-64, OS ABI: Linux 2.6.24) => /usr/lib/x86_64-linux-gnu/libnsl.so
        libnih.so.1 (libc6,x86-64) => /lib/x86_64-linux-gnu/libnih.so.1
        libnih-dbus.so.1 (libc6,x86-64) => /lib/x86_64-linux-gnu/libnih-dbus.so.1
        libnewt.so.0.52 (libc6,x86-64) => /lib/x86_64-linux-gnu/libnewt.so.0.52
        libncursesw.so.5 (libc6,x86-64) => /lib/x86_64-linux-gnu/libncursesw.so.5
        libncurses.so.5 (libc6,x86-64) => /lib/x86_64-linux-gnu/libncurses.so.5
        libmpfr.so.4 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libmpfr.so.4
        libmpdec.so.2 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libmpdec.so.2
        libmpc.so.3 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libmpc.so.3
        libmount.so.1 (libc6,x86-64) => /lib/x86_64-linux-gnu/libmount.so.1
        libmenuw.so.5 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libmenuw.so.5
        libmenu.so.5 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libmenu.so.5
        libmemusage.so (libc6,x86-64, OS ABI: Linux 2.6.24) => /lib/x86_64-linux-gnu/libmemusage.so
        libmagic.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libmagic.so.1
        libm.so.6 (libc6,x86-64, OS ABI: Linux 2.6.24) => /lib/x86_64-linux-gnu/libm.so.6
        libm.so (libc6,x86-64, OS ABI: Linux 2.6.24) => /usr/lib/x86_64-linux-gnu/libm.so
        liblzma.so.5 (libc6,x86-64) => /lib/x86_64-linux-gnu/liblzma.so.5
        liblockfile.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/liblockfile.so.1
        libldap_r-2.4.so.2 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libldap_r-2.4.so.2
        liblber-2.4.so.2 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/liblber-2.4.so.2
        libk5crypto.so.3 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libk5crypto.so.3
        libkrb5support.so.0 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libkrb5support.so.0
        libkrb5.so.26 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libkrb5.so.26
        libkrb5.so.3 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libkrb5.so.3
        libkmod.so.2 (libc6,x86-64) => /lib/x86_64-linux-gnu/libkmod.so.2
        libkeyutils.so.1 (libc6,x86-64) => /lib/x86_64-linux-gnu/libkeyutils.so.1
        libjson-c.so.2 (libc6,x86-64) => /lib/x86_64-linux-gnu/libjson-c.so.2
        libitm.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libitm.so.1
        libisl.so.10 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libisl.so.10
        libidn.so.11 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libidn.so.11
        libhx509.so.5 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libhx509.so.5
        libhistory.so.6 (libc6,x86-64) => /lib/x86_64-linux-gnu/libhistory.so.6
        libheimntlm.so.0 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libheimntlm.so.0
        libheimbase.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libheimbase.so.1
        libhcrypto.so.4 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libhcrypto.so.4
        libgthread-2.0.so.0 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libgthread-2.0.so.0
        libgssapi_krb5.so.2 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2
        libgssapi.so.3 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libgssapi.so.3
        libgpg-error.so.0 (libc6,x86-64) => /lib/x86_64-linux-gnu/libgpg-error.so.0
        libgomp.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libgomp.so.1
        libgobject-2.0.so.0 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
        libgnutls.so.26 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libgnutls.so.26
        libgnutls-openssl.so.27 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libgnutls-openssl.so.27
        libgnutls-extra.so.26 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libgnutls-extra.so.26
        libgmp.so.10 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libgmp.so.10
        libgmodule-2.0.so.0 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libgmodule-2.0.so.0
        libglib-2.0.so.0 (libc6,x86-64) => /lib/x86_64-linux-gnu/libglib-2.0.so.0
        libgirepository-1.0.so.1 (libc6,x86-64) => /usr/lib/libgirepository-1.0.so.1
        libgio-2.0.so.0 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
        libgdbm_compat.so.3 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libgdbm_compat.so.3
        libgdbm.so.3 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libgdbm.so.3
        libgcrypt.so.11 (libc6,x86-64) => /lib/x86_64-linux-gnu/libgcrypt.so.11
        libgcc_s.so.1 (libc6,x86-64) => /lib/x86_64-linux-gnu/libgcc_s.so.1
        libfribidi.so.0 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libfribidi.so.0
        libfreetype.so.6 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libfreetype.so.6
        libfreetype.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libfreetype.so
        libformw.so.5 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libformw.so.5
        libform.so.5 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libform.so.5
        libffi.so.6 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libffi.so.6
        libe2p.so.2 (libc6,x86-64) => /lib/x86_64-linux-gnu/libe2p.so.2
        libext2fs.so.2 (libc6,x86-64) => /lib/x86_64-linux-gnu/libext2fs.so.2
        libexpatw.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libexpatw.so.1
        libexpatw.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libexpatw.so
        libexpat.so.1 (libc6,x86-64) => /lib/x86_64-linux-gnu/libexpat.so.1
        libexpat.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libexpat.so
        libestr.so.0 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libestr.so.0
        libedit.so.2 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libedit.so.2
        libdrm.so.2 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libdrm.so.2
        libdl.so.2 (libc6,x86-64, OS ABI: Linux 2.6.24) => /lib/x86_64-linux-gnu/libdl.so.2
        libdl.so (libc6,x86-64, OS ABI: Linux 2.6.24) => /usr/lib/x86_64-linux-gnu/libdl.so
        libdevmapper.so.1.02.1 (libc6,x86-64) => /lib/x86_64-linux-gnu/libdevmapper.so.1.02.1
        libdebconfclient.so.0 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libdebconfclient.so.0
        libdbus-1.so.3 (libc6,x86-64) => /lib/x86_64-linux-gnu/libdbus-1.so.3
        libdbus-glib-1.so.2 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libdbus-glib-1.so.2
        libdb-5.3.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libdb-5.3.so
        libcurl.so.4 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libcurl.so.4
        libcurl-gnutls.so.4 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4
        libcrypto.so.1.0.0 (libc6,x86-64) => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
        libcrypt.so.1 (libc6,x86-64, OS ABI: Linux 2.6.24) => /lib/x86_64-linux-gnu/libcrypt.so.1
        libcrypt.so (libc6,x86-64, OS ABI: Linux 2.6.24) => /usr/lib/x86_64-linux-gnu/libcrypt.so
        libcom_err.so.2 (libc6,x86-64) => /lib/x86_64-linux-gnu/libcom_err.so.2
        libcloog-isl.so.4 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libcloog-isl.so.4
        libcidn.so.1 (libc6,x86-64, OS ABI: Linux 2.6.24) => /lib/x86_64-linux-gnu/libcidn.so.1
        libcidn.so (libc6,x86-64, OS ABI: Linux 2.6.24) => /usr/lib/x86_64-linux-gnu/libcidn.so
        libcgmanager.so.0 (libc6,x86-64) => /lib/x86_64-linux-gnu/libcgmanager.so.0
        libcap.so.2 (libc6,x86-64) => /lib/x86_64-linux-gnu/libcap.so.2
        libc.so.6 (libc6,x86-64, OS ABI: Linux 2.6.24) => /lib/x86_64-linux-gnu/libc.so.6
        libbz2.so.1.0 (libc6,x86-64) => /lib/x86_64-linux-gnu/libbz2.so.1.0
        libbsd.so.0 (libc6,x86-64) => /lib/x86_64-linux-gnu/libbsd.so.0
        libblkid.so.1 (libc6,x86-64) => /lib/x86_64-linux-gnu/libblkid.so.1
        libbfd-2.24-system.so (libc6,x86-64) => /usr/lib/libbfd-2.24-system.so
        libaudit.so.1 (libc6,x86-64) => /lib/x86_64-linux-gnu/libaudit.so.1
        libattr.so.1 (libc6,x86-64) => /lib/x86_64-linux-gnu/libattr.so.1
        libatomic.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libatomic.so.1
        libasn1.so.8 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libasn1.so.8
        libasan.so.0 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libasan.so.0
        libapt-private.so.0.0 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libapt-private.so.0.0
        libapt-pkg.so.4.12 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libapt-pkg.so.4.12
        libapt-inst.so.1.5 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libapt-inst.so.1.5
        libanl.so.1 (libc6,x86-64, OS ABI: Linux 2.6.24) => /lib/x86_64-linux-gnu/libanl.so.1
        libanl.so (libc6,x86-64, OS ABI: Linux 2.6.24) => /usr/lib/x86_64-linux-gnu/libanl.so
        libacl.so.1 (libc6,x86-64) => /lib/x86_64-linux-gnu/libacl.so.1
        libX11.so.6 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libX11.so.6
        libXmuu.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libXmuu.so.1
        libXext.so.6 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libXext.so.6
        libXdmcp.so.6 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6
        libXau.so.6 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libXau.so.6
        libSegFault.so (libc6,x86-64, OS ABI: Linux 2.6.24) => /lib/x86_64-linux-gnu/libSegFault.so
        libBrokenLocale.so.1 (libc6,x86-64, OS ABI: Linux 2.6.24) => /lib/x86_64-linux-gnu/libBrokenLocale.so.1
        libBrokenLocale.so (libc6,x86-64, OS ABI: Linux 2.6.24) => /usr/lib/x86_64-linux-gnu/libBrokenLocale.so
        ld-linux-x86-64.so.2 (libc6,x86-64) => /lib/x86_64-linux-gnu/ld-linux-x86-64.so.2
0   
```

**Comment by rbharath** [comment]
(Don't mind repeated posts here; mostly using this thread to help me keep track of my debugging :-))

Looks like `ldconfig` can't stat `/usr/local/cuda/lib64`

```/sbin/ldconfig.real: Can't stat ldconfig /usr/local/cuda/lib64: No such file or directory```

**Comment by rbharath** [comment]
I managed to get `ldconfig -p` to list the `libcuda` files by explicitly calling `sudo ldconfig /usr/local/cuda/lib64`, but I'm still seeing the same error as before with tensorflow not seeing GPU. I can also duplicate the error when I'm not building for Sherlock, but for my Ubuntu 16.04 dev-box. I've kicked off a thread on the singularity google group [here](https://groups.google.com/a/lbl.gov/forum/#!topic/singularity/iWOx9PMvPzo) giving full details on the issue. Hopefully someone there will have ideas :-)

**Comment by raphtown** [comment]
Hm, this is indeed intriguing.  Can you try one more thing for me?  Use my singularity install at /scratch/users/raphtown/tf-gpu.img and see if you can see GPU devices from there?  This works for me.

**Comment by rbharath** [comment]
Looks like I can't access your image. Permissions issue?

```
(deepchem) [rbharath@gpu-9-2 ~]$ module load singularity
(deepchem) [rbharath@gpu-9-2 ~]$ singularity run /scratch/users/raphtown/tf-gpu.img
ERROR  : Container not found: /scratch/users/raphtown/tf-gpu.img
ABORT  : Retval = 255
```

**Comment by raphtown** [comment]
Hey Bart, just as a follow-up to this, I have this working again.  Based off of what Eliot said in the Google Groups thread I figured out the issue was that we were getting the CPU version of tensorflow from Docker instead of GPU.  So I switched the code to using pip to install tensorflow instead.  If you do get around to trying this again, let me know if you have any further issues.

**Comment by rbharath** [comment]
Awesome bugfix! Will check it out (likely once Tensorflow 1.0 releases :-))
